// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WardrobeInventory.Data;

#nullable disable

namespace WardrobeInventory.Data.Migrations
{
    [DbContext(typeof(WardrobeContext))]
    partial class WardrobeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("WardrobeInventory.Entities.WardrobeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WardrobeItems");
                });

            modelBuilder.Entity("WardrobeInventory.Entities.WardrobeItemImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("WardrobeId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("WardrobeImage")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("WardrobeId")
                        .IsUnique();

                    b.ToTable("WardrobeItemImages");
                });

            modelBuilder.Entity("WardrobeInventory.Entities.WardrobeItemImage", b =>
                {
                    b.HasOne("WardrobeInventory.Entities.WardrobeItem", "WardrobeItem")
                        .WithOne("WardrobeItemImage")
                        .HasForeignKey("WardrobeInventory.Entities.WardrobeItemImage", "WardrobeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WardrobeItem");
                });

            modelBuilder.Entity("WardrobeInventory.Entities.WardrobeItem", b =>
                {
                    b.Navigation("WardrobeItemImage");
                });
#pragma warning restore 612, 618
        }
    }
}
